### ISSUE TITLE
YonV: Don't open Issues like this 不建议像这样开问题 → Found dtype Double but expected Float

### ISSUE THREAD

**Issue by birdfine** [Yonv1943/ElegantRL#9]
![image](https://user-images.githubusercontent.com/49951200/95939102-ee482000-0e0d-11eb-9047-54bad313fc2d.png)
This problem seems to appear in a lot of the code I downloaded, is my tool version wrong? Please help me to solve it, thank you!

**Comment by Yonv1943** [comment]
YonV: Don't open Issues like this 不建议像这样开问题 → Found dtype Double but expected Float

**The error message has made it very clear**: it needs to accept float instead of double data. Then use the code to convert the data format. This kind of problem is not recommended to occupy the page of Issue for solution.
报错信息已经非常清楚地表明：它需要接受 float 而非 double 的数据。那么使用代码对数据格式进行转换就解决了。这种问题不建议占用 Issue 的版面寻求解决。
```
array = np.array(array, dtype=np.floate32)
array = array.astype(np.float32)  
```

**Comment by birdfine** [comment]
好的，谢谢！

**Comment by birdfine** [comment]
critic_loss = self.criterion(q1_value, q_target.type_as(q1_value)) + self.criterion(q2_value, q_target.type_as(q1_value))
解决了谢谢  这个地方强转一下就行了   慢慢摸索还是能行的
